---
# Configuration for pre-commit
exclude: |
  (?x)(
    ^src/tests/data/.* |
    ^resources/.*
  )
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: 'v0.12.11'
    hooks:
      - id: ruff-check
        args: [--fix]
      - id: ruff-format

  - repo: https://github.com/python-poetry/poetry
    rev: '1.8.0'
    hooks:
      - id: poetry-export
        args: [
          "-f", "requirements.txt",
          "-o", "requirements.txt",
          "--without-hashes"
        ]
