---
# Update README.md with the latest output from rssfixer --help
# and the current status of the bandit check.

name: Update README.md

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  update_readme:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'

      - name: Install markdown-code-runner and bandit
        run: |
          python -m pip install --upgrade pip
          python -m pip install markdown-code-runner bandit

      # Install rssfixer
      - name: Install other Python dependencies
        run: |
          python -m pip install -e .

      # Run bandit
      - name: Run bandit
        run: bandit -l -f json -o resources/bandit.json -r src/rssfixer

      # yamllint disable rule:line
      - name: Commit updated bandit.json
        id: commit_bandit
        run: |
          git add resources/bandit.json
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          if git diff --quiet && git diff --staged --quiet; then
            echo "No changes in bandit.json, skipping commit."
            echo "commit_status=skipped" >> "$GITHUB_ENV"
          else
            git commit -m "Update bandit.json"
            echo "commit_status=committed" >> "$GITHUB_ENV"
          fi
      # yamllint enable

      - name: Push changes
        if: env.commit_status == 'committed'
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.head_ref }}

      - name: Run update-readme.py
        run: markdown-code-runner --verbose README.md

      # yamllint disable rule:line
      - name: Commit updated README.md
        id: commit_readme
        run: |
          git add README.md
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          if git diff --quiet && git diff --staged --quiet; then
            echo "No changes in README.md, skipping commit."
            echo "commit_status=skipped" >> "$GITHUB_ENV"
          else
            git commit -m "Update README.md"
            echo "commit_status=committed" >> "$GITHUB_ENV"
          fi
      # yamllint enable

      - name: Push changes
        if: env.commit_status == 'committed'
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.head_ref }}
